import { StyleSheet } from 'react-native';
import { theme } from '../../theme/theme';

export const xerpaAIStyles = StyleSheet.create({
  safeContainer: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  container: {
    flex: 1,
  },
  chatInner: {
    flex: 1,
  },
  messagesListWrapper: {
    flex: 1,
  },
  messagesList: {
    flexGrow: 1,
    paddingVertical: 20,
    paddingBottom: 8,
    paddingHorizontal: theme.SCREEN_PADDING_HORIZONTAL,
  },
  bubbleUser: {
    alignSelf: 'flex-end',
    backgroundColor: '#1E1E1E',
    borderRadius: 18,
    borderTopRightRadius: 4,
    padding: 14,
    maxWidth: '80%',
    marginBottom: 12,
  },
  bubbleAssistant: {
    alignSelf: 'flex-start',
    backgroundColor: '#000000',
    borderRadius: 18,
    borderTopLeftRadius: 4,
    padding: 14,
    maxWidth: '80%',
    marginBottom: 12,
    borderWidth: 2,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 4,
  },
  bubbleTextUser: {
    color: '#fff',
    fontSize: 15,
    lineHeight: 22,
  },
  bubbleTextAssistant: {
    color: '#ddd',
    fontSize: 15,
    lineHeight: 22,
  },
  typingContainer: {
    alignSelf: 'flex-start',
    marginBottom: 12,
  },
  typingBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#000000',
    borderRadius: 18,
    borderTopLeftRadius: 4,
    padding: 14,
    borderWidth: 2,
    borderColor: '#39FF14',
    gap: 10,
    shadowColor: '#39FF14',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  typingText: {
    color: '#888',
    fontSize: 14,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    width: '100%',
    paddingHorizontal: theme.SCREEN_PADDING_HORIZONTAL,
    paddingTop: 12,
    paddingBottom: 12,
    marginBottom: 0,
    gap: 12,
    backgroundColor: theme.colors.background,
    borderTopWidth: 1,
    borderTopColor: '#1A1A1A',
  },
  chatInput: {
    flex: 1,
    backgroundColor: '#1E1E1E',
    color: '#fff',
    paddingLeft: 15,
    paddingRight: 14,
    paddingTop: 12,
    paddingBottom: 12,
    borderRadius: 24,
    fontSize: theme.INPUT_FONT_SIZE_MIN,
    lineHeight: 22,
    borderWidth: 1,
    borderColor: '#333',
    textAlignVertical: 'top',
  },
  sendButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#39FF14',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendButtonDisabled: {
    opacity: 0.5,
  },
});
