import { StyleSheet } from 'react-native';

export const dashboardStyles = StyleSheet.create({
  safeContainer: {
    flex: 1,
    backgroundColor: '#121212',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 24,
    paddingBottom: 38,
  },
  header: {
    marginBottom: 24,
  },
  headerGreeting: {
    color: '#888',
    fontSize: 15,
    fontWeight: '500',
  },
  headerName: {
    color: '#fff',
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  progressCircle: {
    width: 92,
    height: 92,
    minWidth: 92,
    minHeight: 92,
    borderRadius: 46,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#181818',
    shadowColor: '#39FF14',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 14,
    borderColor: '#39FF14',
    borderWidth: 2,
  },
  progressCircleInner: {
    width: 92,
    height: 92,
    borderRadius: 46,
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressCircleText: {
    color: '#39FF14',
    fontWeight: '700',
    fontSize: 18,
    letterSpacing: 2,
    textAlign: 'center',
  },
  statusWidget: {
    backgroundColor: '#191e1a',
    borderRadius: 18,
    padding: 24,
    borderWidth: 2,
    borderColor: '#39FF14',
    alignItems: 'center',
    marginBottom: 24,
    shadowColor: '#39FF14',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  statusWidgetText: {
    color: '#888',
    fontSize: 13,
    marginTop: 12,
    fontWeight: '500',
  },
  statusWidgetValue: {
    color: '#fff',
    fontWeight: '700',
  },
  workoutCardGradient: {
    borderRadius: 18,
    marginBottom: 24,
    padding: 3,
    shadowColor: '#00F0FF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.32,
    shadowRadius: 12,
  },
  workoutCardInner: {
    backgroundColor: '#181818',
    borderRadius: 16,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  workoutCardIconContainer: {
    backgroundColor: '#111',
    borderRadius: 10,
    padding: 12,
    marginRight: 18,
    alignItems: 'center',
  },
  workoutCardIconLabel: {
    color: '#39FF14',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 2,
  },
  workoutCardContent: {
    flex: 1,
  },
  workoutCardTitle: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '700',
  },
  workoutCardSubtext: {
    color: '#888',
    fontWeight: '500',
    marginTop: 2,
    fontSize: 14,
  },
  workoutCardSubtextHighlight: {
    color: '#fff',
  },
  workoutCardIntensity: {
    color: '#ffca28',
    fontWeight: 'bold',
  },
  quickMetricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 34,
  },
  metricCard: {
    flex: 1,
    backgroundColor: '#181818',
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    marginRight: 7,
    borderWidth: 1,
    borderColor: '#00F0FF55',
    shadowColor: '#00F0FF',
    shadowOpacity: 0.12,
    shadowRadius: 7,
  },
  metricCardLast: {
    marginRight: 0,
  },
  metricCardTsb: {
    borderColor: '#ff9800aa',
    shadowColor: '#ff9800',
    shadowOpacity: 0.22,
  },
  metricValue: {
    fontWeight: '700',
    fontSize: 24,
  },
  metricValueCtl: {
    color: '#39FF14',
  },
  metricValueAtl: {
    color: '#00F0FF',
  },
  metricValueTsb: {
    color: '#ff9800',
  },
  metricLabel: {
    color: '#bbb',
    fontSize: 13,
    marginTop: 4,
  },
  metricSublabel: {
    color: '#666',
    fontSize: 11,
  },
  emptyState: {
    backgroundColor: '#181818',
    borderRadius: 18,
    padding: 32,
    alignItems: 'center',
    marginBottom: 24,
    borderWidth: 2,
    borderColor: '#333',
    borderStyle: 'dashed',
  },
  emptyStateTitle: {
    color: '#00F0FF',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyStateText: {
    color: '#888',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 22,
  },
  emptyStateLink: {
    color: '#39FF14',
    fontWeight: '600',
    marginTop: 12,
  },
  reportButton: {
    width: '100%',
    marginTop: 20,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#39FF14',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
  },
  reportButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    paddingHorizontal: 24,
    gap: 10,
  },
  reportButtonText: {
    color: '#121212',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  vincularLink: {
    marginTop: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalContent: {
    backgroundColor: '#121212',
    borderRadius: 20,
    padding: 28,
    width: '100%',
    maxWidth: 340,
    borderWidth: 2,
    borderColor: '#39FF14',
  },
  modalTitle: {
    color: '#39FF14',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 8,
    textAlign: 'center',
  },
  modalSubtitle: {
    color: '#888',
    fontSize: 14,
    marginBottom: 20,
    textAlign: 'center',
  },
  modalInput: {
    backgroundColor: '#1E1E1E',
    color: '#fff',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333',
    fontSize: 18,
    marginBottom: 24,
    textAlign: 'center',
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  modalCancelButton: {
    flex: 1,
    padding: 14,
    borderRadius: 12,
    backgroundColor: '#1E1E1E',
    alignItems: 'center',
  },
  modalCancelText: {
    color: '#888',
    fontSize: 16,
  },
  modalSubmitButton: {
    flex: 1,
    padding: 14,
    borderRadius: 12,
    backgroundColor: '#39FF14',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
  },
  modalSubmitText: {
    color: '#121212',
    fontSize: 16,
    fontWeight: '700',
  },
  rpeCard: {
    backgroundColor: '#1E1E1E',
    borderRadius: 18,
    padding: 28,
    marginBottom: 24,
    borderWidth: 2,
    elevation: 6,
  },
  rpeCardTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 20,
    textAlign: 'center',
  },
  rpeNumberContainer: {
    alignItems: 'center',
    marginBottom: 16,
  },
  rpeNumber: {
    fontSize: 56,
    fontWeight: '900',
    letterSpacing: -2,
  },
  rpeLabel: {
    fontSize: 15,
    fontWeight: '600',
    marginTop: 8,
    textAlign: 'center',
  },
  rpeSlider: {
    width: '100%',
    height: 40,
    marginBottom: 24,
  },
  rpeSaveButton: {
    width: '100%',
    borderRadius: 14,
    overflow: 'hidden',
  },
  rpeSaveButtonGradient: {
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rpeSaveButtonText: {
    color: '#121212',
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  rpeSuccessCard: {
    backgroundColor: '#1E1E1E',
    borderRadius: 18,
    padding: 24,
    marginBottom: 24,
    borderWidth: 2,
    borderColor: '#39FF14',
    alignItems: 'center',
    shadowColor: '#39FF14',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  rpeSuccessText: {
    color: '#39FF14',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
});
