import React from 'react';
import { usePerfil } from './usePerfil';
import { PerfilView } from './PerfilView';
import { perfilStyles } from './PerfilStyles';

export default function PerfilScreen({ user }) {
  const {
    profileData,
    loading,
    isSavingPerfil,
    nombre,
    setNombre,
    nombreError,
    rol,
    setRol,
    edad,
    setEdad,
    tallaCm,
    setTallaCm,
    pesoKg,
    setPesoKg,
    modalidad,
    setModalidad,
    categoria,
    setCategoria,
    email,
    handleGuardarBiometria,
    handleGuardarPreferencias,
    handleInsertContacto,
    handleUpdateContacto,
    handleDeleteContacto,
    handleLogout,
    handleStravaAuthSuccess,
    handleVincularIntervalos,
    handlePlatformPress,
    handleDisconnect,
    handleCloseDisconnectModal,
    handleConfirmDisconnect,
    platformToDisconnect,
    disconnectingPlatform,
    codigoVinculacion,
    handleCopyCodigo,
    handleShareCodigo,
    showIntervalosSheet,
    idExterno,
    setIdExterno,
    apiKeyIntervalos,
    setApiKeyIntervalos,
    intervalosError,
    isSavingIntervalos,
    handleCerrarIntervalosSheet,
    handleGuardarIntervalos,
    codigoIngresado,
    setCodigoIngresado,
    handleCodigoIngresadoChange,
    handleBuscarCodigo,
    previewVinculado,
    buscarLoading,
    handleClosePreviewVinculacion,
    handleConfirmVinculacion,
    vincularLoading,
    vincularError,
    relacionesEntrenadores,
    relacionesTutores,
    relacionToDesvincular,
    handleDesvincular,
    handleCloseDesvincularModal,
    handleConfirmDesvincular,
    desvincularLoading,
    showPasswordSheet,
    newPassword,
    setNewPassword,
    confirmPassword,
    setConfirmPassword,
    passwordError,
    isUpdatingPassword,
    handleAbrirCambioContrasena,
    handleCerrarCambioContrasena,
    handleGuardarContrasena,
    refreshUserData,
    showBiometriaSheet,
    showNotificacionesSheet,
    handleOpenBiometriaSheet,
    handleCloseBiometriaSheet,
    handleOpenNotificacionesSheet,
    handleCloseNotificacionesSheet,
    showToast,
  } = usePerfil(user);

  return (
    <PerfilView
      profileData={profileData}
      loading={loading}
      nombre={nombre}
      setNombre={setNombre}
      nombreError={nombreError}
      rol={rol}
      setRol={setRol}
      edad={edad}
      setEdad={setEdad}
      tallaCm={tallaCm}
      setTallaCm={setTallaCm}
      pesoKg={pesoKg}
      setPesoKg={setPesoKg}
      modalidad={modalidad}
      setModalidad={setModalidad}
      categoria={categoria}
      setCategoria={setCategoria}
      email={email}
      isSavingPerfil={isSavingPerfil}
      handleGuardarBiometria={handleGuardarBiometria}
      handleGuardarPreferencias={handleGuardarPreferencias}
      handleInsertContacto={handleInsertContacto}
      handleUpdateContacto={handleUpdateContacto}
      handleDeleteContacto={handleDeleteContacto}
      handleLogout={handleLogout}
      handleStravaAuthSuccess={handleStravaAuthSuccess}
      handleVincularIntervalos={handleVincularIntervalos}
      handlePlatformPress={handlePlatformPress}
      handleDisconnect={handleDisconnect}
      handleCloseDisconnectModal={handleCloseDisconnectModal}
      handleConfirmDisconnect={handleConfirmDisconnect}
      platformToDisconnect={platformToDisconnect}
      disconnectingPlatform={disconnectingPlatform}
    codigoVinculacion={codigoVinculacion}
    handleCopyCodigo={handleCopyCodigo}
    handleShareCodigo={handleShareCodigo}
      showIntervalosSheet={showIntervalosSheet}
      idExterno={idExterno}
      setIdExterno={setIdExterno}
      apiKeyIntervalos={apiKeyIntervalos}
      setApiKeyIntervalos={setApiKeyIntervalos}
      intervalosError={intervalosError}
      isSavingIntervalos={isSavingIntervalos}
      handleCerrarIntervalosSheet={handleCerrarIntervalosSheet}
      handleGuardarIntervalos={handleGuardarIntervalos}
      codigoIngresado={codigoIngresado}
      handleCodigoIngresadoChange={handleCodigoIngresadoChange}
      handleBuscarCodigo={handleBuscarCodigo}
      previewVinculado={previewVinculado}
      buscarLoading={buscarLoading}
      onClosePreview={handleClosePreviewVinculacion}
      onConfirmVinculacion={handleConfirmVinculacion}
      vincularLoading={vincularLoading}
      vincularError={vincularError}
      relacionesEntrenadores={relacionesEntrenadores}
      relacionesTutores={relacionesTutores}
      relacionToDesvincular={relacionToDesvincular}
      onDesvincular={handleDesvincular}
      onCloseDesvincularModal={handleCloseDesvincularModal}
      onConfirmDesvincular={handleConfirmDesvincular}
      desvincularLoading={desvincularLoading}
      showPasswordSheet={showPasswordSheet}
      newPassword={newPassword}
      setNewPassword={setNewPassword}
      confirmPassword={confirmPassword}
      setConfirmPassword={setConfirmPassword}
      passwordError={passwordError}
      isUpdatingPassword={isUpdatingPassword}
      handleAbrirCambioContrasena={handleAbrirCambioContrasena}
      handleCerrarCambioContrasena={handleCerrarCambioContrasena}
      handleGuardarContrasena={handleGuardarContrasena}
      refreshUserData={refreshUserData}
      showBiometriaSheet={showBiometriaSheet}
      showNotificacionesSheet={showNotificacionesSheet}
      handleOpenBiometriaSheet={handleOpenBiometriaSheet}
      handleCloseBiometriaSheet={handleCloseBiometriaSheet}
      handleOpenNotificacionesSheet={handleOpenNotificacionesSheet}
      handleCloseNotificacionesSheet={handleCloseNotificacionesSheet}
      showToast={showToast}
      styles={perfilStyles}
    />
  );
}
