import { StyleSheet, Platform } from 'react-native';
import { theme } from '../../theme/theme';

const ROL_OPTIONS = ['Atleta', 'Entrenador', 'Tutor'];
const CARD_SHADOW = theme.shadow({ color: '#000', opacity: 0.2, radius: 12, elevation: 6 });

export { ROL_OPTIONS };

export const perfilStyles = StyleSheet.create({
  safeContainer: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: theme.SCREEN_PADDING_HORIZONTAL,
    paddingTop: 20,
    paddingBottom: 38,
  },
  headerActionTouchable: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerActionTrigger: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0, 210, 255, 0.05)',
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#00D2FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
      },
      android: { elevation: 3 },
      default: {},
    }),
  },
  title: {
    color: '#fff',
    fontSize: 26,
    fontWeight: '800',
    marginBottom: 24,
    letterSpacing: 0.5,
  },
  section: {
    marginBottom: 28,
  },
  // ── Dashboard: Identity Header ─────────────────────────────
  identityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    ...CARD_SHADOW,
  },
  identityAvatarWrap: { marginRight: 16 },
  identityAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(0,240,255,0.15)',
    borderWidth: 2,
    borderColor: 'rgba(0,240,255,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  identityAvatarText: {
    color: '#00F0FF',
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: 1,
  },
  identityContent: { flex: 1, justifyContent: 'center' },
  identityName: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 2,
  },
  identityEmail: {
    color: '#888',
    fontSize: 14,
  },
  identityEditBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: theme.TOUCH_TARGET_MIN,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: 'rgba(0,240,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(0,240,255,0.35)',
  },
  identityEditText: {
    color: '#00F0FF',
    fontSize: 13,
    fontWeight: '700',
  },

  // ── Dashboard: Social ID Card (tarjeta crédito / licencia) ──
  userIdCard: {
    borderRadius: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(0,240,255,0.25)',
    overflow: 'hidden',
    ...CARD_SHADOW,
  },
  userIdCardInner: {
    padding: 24,
    alignItems: 'center',
  },
  userIdLabel: {
    color: '#00F0FF',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 3,
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  userIdValue: {
    color: '#fff',
    fontSize: 36,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontWeight: '800',
    letterSpacing: 5,
    marginBottom: 24,
    textAlign: 'center',
  },
  userIdActions: {
    flexDirection: 'row',
    gap: 16,
  },
  userIdActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 12,
    backgroundColor: 'rgba(0,240,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(0,240,255,0.35)',
  },
  userIdActionText: {
    color: '#00F0FF',
    fontSize: 13,
    fontWeight: '700',
  },
  userIdActionBtnDisabled: {
    opacity: 0.5,
  },
  userIdActionTextDisabled: {
    color: '#444',
  },

  // ── Dashboard: Read-only rows ──────────────────────────────
  dashboardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#252525',
  },
  dashboardLabel: {
    color: '#666',
    fontSize: 14,
  },
  dashboardValue: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  biometriaProgressWrap: {
    marginBottom: 10,
  },
  biometriaProgressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  biometriaProgressLabel: {
    color: '#8E8E93',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  biometriaProgressValue: {
    color: '#00D2FF',
    fontSize: 12,
    fontWeight: '800',
  },
  dashboardEditBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,240,255,0.4)',
    backgroundColor: 'rgba(0,240,255,0.08)',
    alignSelf: 'flex-start',
  },
  dashboardEditText: {
    color: '#00F0FF',
    fontSize: 13,
    fontWeight: '700',
  },

  // ── Sheets (BottomSheet forms, unificado con RaceCalendar) ──
  sheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: '#1A1A1A',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: theme.SHEET_PADDING_BOTTOM,
    borderTopWidth: 1,
    borderColor: '#2A2A2A',
    maxHeight: '92%',
  },
  sheetHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#333',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  sheetTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 6,
  },
  sheetSubtitle: {
    color: '#555',
    fontSize: 13,
    marginBottom: 20,
  },
  sheetLabel: {
    color: '#555',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  sheetInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#121212',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    marginBottom: 16,
  },
  sheetInputError: { borderColor: '#ff5252' },
  sheetInput: {
    flex: 1,
    color: '#fff',
    fontSize: theme.INPUT_FONT_SIZE_MIN,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  sheetErrorText: {
    color: '#ff5252',
    fontSize: 12,
    marginTop: -12,
    marginBottom: 12,
  },
  sheetRow: { flexDirection: 'row', gap: 12 },
  sheetRowItem: { flex: 1 },
  sheetRolRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  sheetRolPill: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    backgroundColor: '#121212',
    alignItems: 'center',
  },
  sheetRolPillActive: {
    borderColor: '#00F0FF',
    backgroundColor: 'rgba(0,240,255,0.12)',
  },
  sheetRolPillText: {
    color: '#555',
    fontSize: 13,
    fontWeight: '600',
  },
  sheetRolPillTextActive: {
    color: '#00F0FF',
    fontWeight: '800',
  },
  sheetCanalRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  sheetCanalPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    backgroundColor: '#121212',
  },
  sheetCanalPillActive: {
    borderColor: '#00F0FF',
    backgroundColor: 'rgba(0,240,255,0.12)',
  },
  sheetCanalPillText: {
    color: '#555',
    fontSize: 13,
    fontWeight: '600',
  },
  sheetCanalPillTextActive: {
    color: '#121212',
    fontWeight: '800',
  },
  sheetSwitchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  sheetSwitchLabel: {
    color: '#ccc',
    fontSize: 14,
    fontWeight: '600',
  },
  sheetActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
    marginBottom: 8,
  },
  sheetCancelBtn: {
    flex: 1,
    height: theme.BUTTON_HEIGHT,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#333',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetCancelText: {
    color: '#888',
    fontSize: 14,
    fontWeight: '700',
  },
  sheetSaveBtn: {
    flex: 1.6,
    borderRadius: 14,
    overflow: 'hidden',
  },
  sheetSaveGradient: {
    height: theme.BUTTON_HEIGHT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetSaveText: {
    color: '#121212',
    fontSize: 14,
    fontWeight: '800',
  },

  // ── Cards (tarjetas modulares) ─────────────────────────────
  card: {
    backgroundColor: '#1A1A1A',
    borderRadius: 18,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    ...CARD_SHADOW,
  },
  cardTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: -0.3,
    marginBottom: 18,
    textTransform: 'capitalize',
  },
  inputReadOnly: {
    color: '#888',
  },
  row: {
    flexDirection: 'row',
    gap: 12,
  },
  rowItem: {
    flex: 1,
  },
  emptyText: {
    color: '#666',
    fontSize: 14,
    marginBottom: 16,
    lineHeight: 20,
  },
  // Canal pills (notificaciones)
  canalRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  canalPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    backgroundColor: '#121212',
  },
  canalPillActive: {
    borderColor: '#00F0FF',
    backgroundColor: 'rgba(0,240,255,0.12)',
  },
  canalPillText: {
    color: '#555',
    fontSize: 13,
    fontWeight: '600',
  },
  canalPillTextActive: {
    color: '#121212',
    fontWeight: '800',
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  switchLabel: {
    color: '#ccc',
    fontSize: 14,
    fontWeight: '600',
  },
  // Contactos de emergencia
  contactoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#252525',
  },
  contactoContent: { flex: 1 },
  contactoNombre: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  contactoMeta: {
    color: '#666',
    fontSize: 13,
    marginTop: 2,
  },
  contactoActions: {
    flexDirection: 'row',
    gap: 8,
  },
  contactoActionBtn: {
    padding: 8,
    paddingHorizontal: 12,
  },
  contactoActionText: {
    color: '#00F0FF',
    fontSize: 13,
    fontWeight: '700',
  },
  contactoActionBtnDanger: {},
  contactoActionTextDanger: {
    color: '#ff5252',
  },
  addContactoBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    marginTop: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,240,255,0.4)',
    borderStyle: 'dashed',
  },
  addContactoText: {
    color: '#00F0FF',
    fontSize: 14,
    fontWeight: '700',
  },
  // Integraciones
  integracionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#252525',
  },
  integracionInfo: { flex: 1 },
  integracionNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  integracionIcon: { marginRight: 2 },
  integracionName: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  integracionBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 6,
  },
  integracionBadgeConnected: {},
  integracionBadgeDisconnected: {},
  integracionBadgeText: {
    fontSize: 12,
    fontWeight: '600',
  },
  integracionBadgeTextConnected: {
    color: '#39FF14',
  },
  integracionBadgeTextDisconnected: {
    color: '#666',
  },
  integracionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,240,255,0.4)',
    backgroundColor: 'rgba(0,240,255,0.08)',
  },
  integracionBtnText: {
    color: '#00F0FF',
    fontSize: 13,
    fontWeight: '700',
  },
  sectionTitle: {
    color: '#00F0FF',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 12,
    letterSpacing: 1,
  },
  input: {
    width: '100%',
    height: theme.INPUT_HEIGHT,
    backgroundColor: '#181818',
    color: '#fff',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333',
    marginBottom: 6,
    fontSize: theme.INPUT_FONT_SIZE_MIN,
  },
  inputError: {
    borderColor: '#ff5252',
    marginBottom: 4,
  },
  inputErrorText: {
    color: '#ff5252',
    fontSize: 12,
    marginBottom: 10,
    lineHeight: 16,
  },
  label: {
    color: '#888',
    fontSize: 12,
    marginBottom: 6,
  },

  // ── Código de vinculación ──────────────────────────────────
  codigoRow: {
    backgroundColor: '#181818',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333',
    padding: 20,
    marginBottom: 16,
    alignItems: 'center',
  },
  codigoValue: {
    color: '#fff',
    fontSize: 24,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    letterSpacing: 3,
    marginBottom: 16,
    textAlign: 'center',
  },
  codigoActions: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
  },
  codigoActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: 'rgba(0,240,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(0,240,255,0.25)',
  },
  codigoActionText: {
    color: '#00F0FF',
    fontSize: 13,
    fontWeight: '700',
  },
  codigoInputSection: {
    marginTop: 16,
    marginBottom: 16,
  },
  codigoVincularBtn: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,240,255,0.3)',
    backgroundColor: 'rgba(0,240,255,0.08)',
  },
  relacionesHint: {
    marginTop: 10,
    color: '#39FF14',
    fontSize: 12,
  },

  // ── Rol pill selector ──────────────────────────────────────
  rolPills: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  rolPill: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    backgroundColor: '#181818',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rolPillActive: {
    borderColor: '#00F0FF',
    backgroundColor: '#00F0FF12',
  },
  rolPillText: {
    color: '#555',
    fontSize: 13,
    fontWeight: '600',
  },
  rolPillTextActive: {
    color: '#00F0FF',
    fontWeight: '800',
  },

  // ── Guardar button (gradient) ──────────────────────────────
  guardarBtn: {
    borderRadius: 14,
    overflow: 'hidden',
    marginTop: 8,
  },
  guardarGradient: {
    height: theme.BUTTON_HEIGHT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  guardarBtnText: {
    color: '#121212',
    fontSize: 15,
    fontWeight: '800',
  },

  button: {
    width: '100%',
    backgroundColor: '#181818',
    borderRadius: 12,
    padding: 16,
    minHeight: theme.BUTTON_HEIGHT,
    height: theme.BUTTON_HEIGHT,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#00F0FF33',
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 12,
  },
  buttonSecurity: {
    borderColor: '#00F0FF55',
    backgroundColor: '#00F0FF08',
  },
  buttonLogout: {
    borderColor: '#ff525233',
    marginTop: 24,
  },
  buttonLogoutText: {
    color: '#ff5252',
  },

  // ── Change Password Bottom Sheet ───────────────────────────
  pwSheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'flex-end',
  },
  pwSheet: {
    backgroundColor: '#1A1A1A',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: theme.SCREEN_PADDING_HORIZONTAL,
    paddingTop: 16,
    paddingBottom: 44,
    borderTopWidth: 1,
    borderColor: '#2A2A2A',
  },
  pwSheetHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#333',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  pwSheetTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 6,
    letterSpacing: -0.3,
  },
  pwSheetSubtitle: {
    color: '#555',
    fontSize: 13,
    marginBottom: 24,
    lineHeight: 18,
  },
  pwLabel: {
    color: '#555',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  pwInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#121212',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2A2A2A',
    marginBottom: 16,
  },
  pwInputWrapperError: {
    borderColor: '#ff5252',
  },
  pwInput: {
    flex: 1,
    color: '#fff',
    fontSize: theme.INPUT_FONT_SIZE_MIN,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  pwEyeBtn: {
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  pwErrorText: {
    color: '#ff5252',
    fontSize: 13,
    marginTop: -8,
    marginBottom: 16,
    lineHeight: 18,
  },
  pwActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  pwCancelBtn: {
    flex: 1,
    height: theme.BUTTON_HEIGHT,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#333',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pwCancelText: {
    color: '#888',
    fontSize: 14,
    fontWeight: '700',
  },
  pwSaveBtn: {
    flex: 1.6,
    borderRadius: 14,
    overflow: 'hidden',
  },
  pwSaveGradient: {
    height: theme.BUTTON_HEIGHT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pwSaveText: {
    color: '#121212',
    fontSize: 14,
    fontWeight: '800',
  },

  // ── Progress Overlays ──────────────────────────────────────
  updatingOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  updatingCard: {
    backgroundColor: '#1A1A1A',
    borderRadius: 24,
    padding: 32,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#00F0FF33',
    width: '100%',
    ...Platform.select({
      ios: { shadowColor: '#00F0FF', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.2, shadowRadius: 20 },
      android: { elevation: 12 },
      default: {},
    }),
  },
  updatingTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 10,
    letterSpacing: -0.3,
  },
  updatingText: {
    color: '#888',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 22,
  },
});
